# Generated by Django 6.0.8 on 2026-09-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_security_hardening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentapitoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='studentapitoken',
            new_name='student_por_expires_f6e4f4_idx',
            old_name='student_por_expires_c8e3ca_idx',
        ),
        migrations.RenameIndex(
            model_name='studentapitoken',
            new_name='student_por_account_43857d_idx',
            old_name='student_por_account_9c190c_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinvitation',
            new_name='student_por_expires_f608ca_idx',
            old_name='student_por_expires_5a4a95_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinvitation',
            new_name='student_por_student_897f08_idx',
            old_name='student_por_student_74f6ce_idx',
        ),
    ]
