# Generated by Django 6.0.8 on 2026-09-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exercise',
            name='exercises_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercise',
            name='exercises_muscle_idx',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(blank=True, max_length=120, verbose_name='Região corporal'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, max_length=80, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category_ptbr',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dificuldade'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty_ptbr',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_ptbr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_main_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_peak_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_start_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions_ptbr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_unilateral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='met',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_ptbr',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle_ptbr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles_ptbr',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source_id',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
