# Generated by Django 6.0.8 on 2026-09-13 20:00

import apps.exercises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_publication_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='media_url',
            field=models.URLField(blank=True, validators=[apps.exercises.models.validate_video_url], verbose_name='Vídeo YouTube/Bilibili'),
        ),
    ]
