# Generated by Django 6.0.8 on 2026-09-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ce_event_t_798924_idx',
            old_name='security_ev_event_t_8ab210_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ce_severit_2fc5cb_idx',
            old_name='security_ev_severit_6e35f4_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ce_ip_addr_9d8039_idx',
            old_name='security_ev_ip_addr_1a4fb4_idx',
        ),
        migrations.RenameIndex(
            model_name='securitythrottle',
            new_name='security_ce_scope_9d5901_idx',
            old_name='security_th_scope_72c9f6_idx',
        ),
        migrations.RenameIndex(
            model_name='securitythrottle',
            new_name='security_ce_blocked_692473_idx',
            old_name='security_th_blocked_4d9320_idx',
        ),
    ]
