# Generated by Django 6.0.8 on 2026-09-13 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_center', '0002_rename_security_ev_event_t_8ab210_idx_security_ce_event_t_798924_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_secret', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_step', models.BigIntegerField(default=-1)),
                ('recovery_code_hashes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
