# Generated by Django 6.0.8 on 2026-09-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_center', '0003_add_mfa_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MFADevice',
        ),
    ]
